Repository OCA/sign, pull requests merged in 2024-03, with the labels that each got.

#8 [14.0][IMP] sign_oca: Systray management + user rules + wizard to create requests
  sign_oca/README.rst
  sign_oca/__manifest__.py
  sign_oca/demo/sign_oca_template.xml
  sign_oca/i18n/sign_oca.pot
  sign_oca/models/__init__.py
  sign_oca/models/res_users.py
  sign_oca/models/sign_oca_request.py
  sign_oca/models/sign_oca_role.py
  sign_oca/models/sign_oca_template.py
  sign_oca/readme/CONFIGURE.rst
  sign_oca/readme/CONTRIBUTORS.rst
  sign_oca/readme/USAGE.rst
  sign_oca/security/ir.model.access.csv
  sign_oca/security/security.xml
  sign_oca/static/description/index.html
  sign_oca/static/src/elements/systray.js
  sign_oca/static/src/elements/systray.xml
  sign_oca/templates/assets.xml
  sign_oca/tests/test_sign.py
  sign_oca/tests/test_sign_portal.py
  sign_oca/views/menu.xml
  sign_oca/views/sign_oca_request.xml
  sign_oca/views/sign_oca_role.xml
  sign_oca/views/sign_oca_template.xml
  sign_oca/wizards/__init__.py
  sign_oca/wizards/sign_oca_template_generate.py
  sign_oca/wizards/sign_oca_template_generate_multi.py
  sign_oca/wizards/sign_oca_template_generate_multi.xml
Labels: bot is merging ⏳

#18 [14.0][FIX] sign_oca: Some fixes
  sign_oca/models/sign_oca_request.py
  sign_oca/views/sign_oca_request.xml
Labels: bot is merging ⏳

#20 [14.0][IMP] sign_oca: Add Sign from template action from tree and form view
  sign_oca/README.rst
  sign_oca/i18n/sign_oca.pot
  sign_oca/models/sign_oca_template.py
  sign_oca/readme/CONFIGURE.rst
  sign_oca/security/security.xml
  sign_oca/static/description/index.html
  sign_oca/static/src/js/sign_oca.js
  sign_oca/templates/assets.xml
  sign_oca/tests/test_sign.py
  sign_oca/wizards/sign_oca_template_generate_multi.py
  sign_oca/wizards/sign_oca_template_generate_multi.xml
Labels: approved

#21 [14.0][FIX] sign_oca: Small fixes in configure mode
  sign_oca/models/sign_oca_request.py
  sign_oca/models/sign_oca_template.py
  sign_oca/static/src/components/sign_oca_configure/sign_oca_configure.xml
  sign_oca/static/src/components/sign_oca_pdf/sign_oca_pdf.js
  sign_oca/static/src/elements/check.js
  sign_oca/static/src/elements/signature.js
  sign_oca/static/src/elements/text.js
Labels: bot is merging ⏳, approved

#9 [14.0][ADD] maintenance_sign_oca: New module
  maintenance_sign_oca/README.rst
  maintenance_sign_oca/__init__.py
  maintenance_sign_oca/__manifest__.py
  maintenance_sign_oca/demo/sign_oca_role.xml
  maintenance_sign_oca/demo/sign_oca_template.xml
  maintenance_sign_oca/i18n/es.po
  maintenance_sign_oca/i18n/maintenance_sign_oca.pot
  maintenance_sign_oca/models/__init__.py
  maintenance_sign_oca/models/maintenance_equipment.py
  maintenance_sign_oca/models/res_company.py
  maintenance_sign_oca/models/res_config_settings.py
  maintenance_sign_oca/models/sign_oca_request.py
  maintenance_sign_oca/oca_dependencies.txt
  maintenance_sign_oca/readme/CONFIGURE.rst
  maintenance_sign_oca/readme/CONTRIBUTORS.rst
  maintenance_sign_oca/readme/DESCRIPTION.rst
  maintenance_sign_oca/readme/USAGE.rst
  maintenance_sign_oca/static/description/icon.png
  maintenance_sign_oca/static/description/index.html
  maintenance_sign_oca/tests/__init__.py
  maintenance_sign_oca/tests/test_maintenance_sign_oca.py
  maintenance_sign_oca/views/maintenance_equipment_views.xml
  maintenance_sign_oca/views/res_config_settings_view.xml
  maintenance_sign_oca/views/sign_oca_request_views.xml
  setup/maintenance_sign_oca/odoo/addons/maintenance_sign_oca
  setup/maintenance_sign_oca/setup.py
Labels: bot is merging ⏳, approved, stale, ready to merge

#19 [14.0][IMP] sign_oca: Link from partner to signer
  sign_oca/README.rst
  sign_oca/__manifest__.py
  sign_oca/models/__init__.py
  sign_oca/models/res_partner.py
  sign_oca/static/description/index.html
  sign_oca/views/res_partner_views.xml
Labels: bot is merging ⏳

#24 [14.0][FIX] sign_oca: Duplicated Sign button in request
  sign_oca/models/sign_oca_request.py
  sign_oca/views/sign_oca_request.xml
Labels: bot is merging ⏳, approved
