Repository OCA/sign, pull requests merged in 2024-05, with the labels that each got.

#22 [16.0][IMP] sign_oca: Improvements migrated from 14.0
  sign_oca/README.rst
  sign_oca/__manifest__.py
  sign_oca/demo/sign_oca_template.xml
  sign_oca/i18n/sign_oca.pot
  sign_oca/migrations/16.0.1.1.1/pre-migration.py
  sign_oca/models/__init__.py
  sign_oca/models/res_partner.py
  sign_oca/models/res_users.py
  sign_oca/models/sign_oca_request.py
  sign_oca/models/sign_oca_role.py
  sign_oca/models/sign_oca_template.py
  sign_oca/readme/CONFIGURE.rst
  sign_oca/readme/CONTRIBUTORS.rst
  sign_oca/readme/USAGE.rst
  sign_oca/security/ir.model.access.csv
  sign_oca/security/security.xml
  sign_oca/static/description/index.html
  sign_oca/static/src/components/sign_oca_configure/sign_oca_configure.xml
  sign_oca/static/src/components/sign_oca_pdf/sign_oca_pdf.esm.js
  sign_oca/static/src/components/sign_oca_pdf_common/sign_oca_pdf_common_action.esm.js
  sign_oca/static/src/elements/check.esm.js
  sign_oca/static/src/elements/signature.esm.js
  sign_oca/static/src/elements/text.esm.js
  sign_oca/static/src/js/ir_model.esm.js
  sign_oca/static/src/js/main.esm.js
  sign_oca/static/src/js/request_group_view.esm.js
  sign_oca/static/src/js/request_groups.esm.js
  sign_oca/static/src/js/sign_oca.esm.js
  sign_oca/static/src/js/signer_menu_container.esm.js
  sign_oca/static/src/js/signer_menu_view.esm.js
  sign_oca/static/src/js/systray.esm.js
  sign_oca/static/src/js/systray_service.esm.js
  sign_oca/static/src/xml/signer_menu_container.xml
  sign_oca/static/src/xml/systray.xml
  sign_oca/tests/test_sign.py
  sign_oca/tests/test_sign_portal.py
  sign_oca/views/menu.xml
  sign_oca/views/res_partner_views.xml
  sign_oca/views/sign_oca_request.xml
  sign_oca/views/sign_oca_role.xml
  sign_oca/views/sign_oca_template.xml
  sign_oca/wizards/__init__.py
  sign_oca/wizards/sign_oca_template_generate.py
  sign_oca/wizards/sign_oca_template_generate_multi.py
  sign_oca/wizards/sign_oca_template_generate_multi.xml
Labels: bot is merging ⏳, approved

#32 [15.0][MIG] maintenance_sign_oca: Migration to 15.0
  maintenance_sign_oca/README.rst
  maintenance_sign_oca/__init__.py
  maintenance_sign_oca/__manifest__.py
  maintenance_sign_oca/demo/sign_oca_role.xml
  maintenance_sign_oca/demo/sign_oca_template.xml
  maintenance_sign_oca/i18n/es.po
  maintenance_sign_oca/i18n/maintenance_sign_oca.pot
  maintenance_sign_oca/models/__init__.py
  maintenance_sign_oca/models/maintenance_equipment.py
  maintenance_sign_oca/models/res_company.py
  maintenance_sign_oca/models/res_config_settings.py
  maintenance_sign_oca/models/sign_oca_request.py
  maintenance_sign_oca/oca_dependencies.txt
  maintenance_sign_oca/readme/CONFIGURE.rst
  maintenance_sign_oca/readme/CONTRIBUTORS.rst
  maintenance_sign_oca/readme/DESCRIPTION.rst
  maintenance_sign_oca/readme/USAGE.rst
  maintenance_sign_oca/static/description/icon.png
  maintenance_sign_oca/static/description/index.html
  maintenance_sign_oca/tests/__init__.py
  maintenance_sign_oca/tests/test_maintenance_sign_oca.py
  maintenance_sign_oca/views/maintenance_equipment_views.xml
  maintenance_sign_oca/views/res_config_settings_view.xml
  maintenance_sign_oca/views/sign_oca_request_views.xml
  setup/maintenance_sign_oca/odoo/addons/maintenance_sign_oca
  setup/maintenance_sign_oca/setup.py
Labels: bot is merging ⏳, approved, ready to merge

#34 [14.0][FIX] sign_oca: Get signer partner info
  sign_oca/models/sign_oca_request.py
Labels: bot is merging ⏳, approved

#35 [15.0][IMP] maintenance_sign_oca: Compatibility with hr_maintenance in tests
  maintenance_sign_oca/models/maintenance_equipment.py
  maintenance_sign_oca/tests/test_maintenance_sign_oca.py
Labels: bot is merging ⏳, approved

#36 [15.0][FIX] sign_oca: Get signer partner info
  sign_oca/models/sign_oca_request.py
  sign_oca/tests/test_sign.py
Labels: bot is merging ⏳, approved

#37 [14.0][FIX] sign_oca: Filter correctly next_items
  sign_oca/static/src/elements/check.js
  sign_oca/static/src/elements/signature.js
  sign_oca/static/src/elements/text.js
Labels: bot is merging ⏳, approved

#38 [16.0][FIX] sign_oca: pre_migration script
  sign_oca/migrations/16.0.1.1.1/pre-migration.py
Labels: bot is merging ⏳

#28 [16.0][FIX] sign_oca: sign_oca_pdf checkFilledAll
  sign_oca/static/src/components/sign_oca_pdf/sign_oca_pdf.esm.js
Labels: bot is merging ⏳

#39 [16.0][FIX] sign_oca: Get signer partner info
  sign_oca/models/sign_oca_request.py
  sign_oca/tests/test_sign.py
Labels: bot is merging ⏳, approved

#40 [15.0][IMP] sign_oca: Redirect at the end of the signature process
  sign_oca/controllers/main.py
  sign_oca/models/sign_oca_request.py
  sign_oca/static/src/components/sign_oca_pdf_portal/sign_oca_pdf_portal.js
  sign_oca/tests/test_sign.py
Labels: bot is merging ⏳, approved

#42 [16.0][IMP] sign_oca: Redirect at the end of the signature process
  sign_oca/controllers/main.py
  sign_oca/models/sign_oca_request.py
  sign_oca/static/src/components/sign_oca_pdf_portal/sign_oca_pdf_portal.esm.js
  sign_oca/tests/test_sign.py
Labels: bot is merging ⏳, approved

#44 [15.0][FIX] sign_oca: Filter correctly next_items
  sign_oca/static/src/elements/check.js
  sign_oca/static/src/elements/signature.js
  sign_oca/static/src/elements/text.js
Labels: bot is merging ⏳, approved

#46 [15.0][IMP] maintenance_sign_oca: Compatibility with hr_maintenance module
  maintenance_sign_oca/models/maintenance_equipment.py
Labels: approved, ready to merge
