Repository OCA/sign, pull requests merged in 2025-04, with the labels that each got.

#101 [16.0][IMP] maintenance_sign_oca: correct the form of role expression
  maintenance_sign_oca/README.rst
  maintenance_sign_oca/readme/CONFIGURE.md
  maintenance_sign_oca/static/description/index.html
Labels: bot is merging ⏳, approved

#104 [16.0][IMP] sign_oca: correct syntax for oject typing
  sign_oca/README.rst
  sign_oca/readme/USAGE.md
  sign_oca/static/description/index.html
Labels: bot is merging ⏳, approved

#102 [FIX] sign_oca: correct syntax and handle js logic
  sign_oca/static/src/elements/check.esm.js
  sign_oca/static/src/elements/signature.esm.js
  sign_oca/static/src/elements/text.esm.js
Labels: bot is merging ⏳, approved

#103 [FIX] sign_oca: restricted company logo max-height to prevent l…
  sign_oca/static/src/components/sign_oca_pdf_portal/sign_oca_pdf_portal.xml
Labels: bot is merging ⏳, approved, ready to merge

#105 [16.0][REF] sign_oca: Remove legacy code
  sign_oca/__manifest__.py
  sign_oca/static/src/components/sign_oca_pdf/sign_oca_pdf.esm.js
  sign_oca/static/src/components/sign_oca_pdf/sign_oca_pdf.xml
  sign_oca/static/src/components/sign_oca_pdf/sign_oca_pdf_action.esm.js
  sign_oca/static/src/components/sign_oca_pdf_portal/sign_oca_pdf_portal.esm.js
  sign_oca/static/src/components/sign_oca_pdf_portal/sign_oca_pdf_portal.xml
Labels: approved
